theme: jekyll-theme-chirpy

# 网页的语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果它的名称与文件夹 `_data/locales` 中的某个文件相同，则布局语言也会被更改，
# 否则，布局语言将使用默认值 'en'。
lang: zh-CN

# 更改为你的时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone:

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Aiden Blog # the main title

tagline: 让我们把代码写成诗吧 # it will display as the subtitle

description: >- # 用于 SEO 元标签和 Atom 订阅源
  技术类博客，主要涉及java/c++/rust,各种分布式计算引擎，以及架构思想

url: "https://aiden-dong.github.io"

github:
  username: aiden-dong # change to your GitHub username

  # twitter:
  #   username: twitter_username # change to your Twitter username

  # social:
  #   # Change to your full name.
  #   # It will be displayed as the default author of the posts and the copyright owner in the Footer
  #   name: your_full_name
  #   email: example@domain.com # change to your email address
  #   links:
  #     # The first element serves as the copyright owner's link
  #     - https://twitter.com/username # change to your Twitter homepage
  #     - https://github.com/username # change to your GitHub homepage
  #     # Uncomment below to add more social links
  #     # - https://www.facebook.com/username
  #     # - https://www.linkedin.com/in/username

  # 网站验证设置
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: aidendong
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: goatcounter

# 首选颜色方案设置。
#
# 注意：保持为空将默认遵循系统的首选颜色，
# 并且在侧边栏左下角会有一个切换按钮，用于在暗色和亮色主题之间切换。
#
# 可用选项：
#
#     light — 使用亮色方案
#     dark — 使用暗色方案
theme_mode: light # [ light | dark]

# 媒体资源的 CDN 端点。
# 请注意，一旦分配，CDN URL
# 将会被添加到所有以 '/' 开头的媒体资源路径（站点头像、帖子图片、音频和视频文件）中。
#
# 例如：'https://cdn.com'
cdn:

# 侧边栏上的头像，支持本地或 CORS 资源
avatar: source/favicons/author.jpg

# 用于 SEO `og:image` 元标签的网站范围社交预览图像的 URL。
# 它可以被前置内容中的自定义 `page.image` 重写。
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # 帖子评论系统的全局开关。保持为空意味着禁用。
  provider: giscus # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: Aiden-Dong/aiden-dong.github.io
    repo_id: R_kgDONCQxjw
    category: Announcements
    category_id: DIC_kwDONCQxj84Cjejw
    mapping: pathname # optional, default to 'pathname'
    strict: 0 # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: zh-CN # optional, default to the value of `site.lang`
    reactions_enabled: 1 # optional, default to the value of `1`

# 自托管静态资产，可选 › https://github.com/cotes2020/chirpy-static-assets
# assets:
#   self_host:
#     enabled: # boolean, keep empty means false
#     # specify the Jekyll environment, empty means both
#     # only works if `assets.self_host.enabled` is 'true'
#     env: # [development | production]

# pwa:
#   enabled: true # The option for PWA feature (installable)
#   cache:
#     enabled: true # The option for PWA offline cache
#     # Paths defined here will be excluded from the PWA cache.
#     # Usually its value is the `baseurl` of another website that
#     # shares the same domain name as the current website.
#     deny_paths:
#       # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
